In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a.shape

(3,)

In [4]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [6]:
a[0]

np.int64(1)

In [7]:
a[1:3]

array([2, 3])

In [11]:
print(np.mean(a))

2.0


In [12]:
print(np.sum(a))

6


In [13]:
print(np.std(a))

0.816496580927726


In [14]:
np.where(a>1,1,0)

array([0, 1, 1])

a[a>1]