In [1]:
import numpy as np

In [2]:
a=np.array([20,30,40,50])

In [3]:
b=np.arange(4)

In [4]:
b

array([0, 1, 2, 3])

In [6]:
c=a-b
c

array([20, 29, 38, 47])

In [7]:
b**2

array([0, 1, 4, 9])

In [8]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [9]:
a<35

array([ True,  True, False, False])

In [12]:
A=np.array([[1,1],[0,1]])

In [13]:
B=np.array([[2,0],[3,4]])

In [14]:
A*B

array([[2, 0],
       [0, 4]])

In [15]:
A@B

array([[5, 4],
       [3, 4]])

In [16]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [17]:
rg=np.random.default_rng(1)

In [18]:
a=np.ones((2,3),dtype=int)

In [19]:
b=rg.random((2,3))

In [21]:
a*=3
a

array([[9, 9, 9],
       [9, 9, 9]])

In [22]:
b+=a
b

array([[9.51182162, 9.9504637 , 9.14415961],
       [9.94864945, 9.31183145, 9.42332645]])

In [23]:
a+=b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [27]:
from numpy import pi
a=np.ones(3,dtype=np.int32)

In [29]:
b=np.linspace(0,pi,3)
b

array([0.        , 1.57079633, 3.14159265])

In [30]:
b.dtype.name

'float64'